name: radio20158
description: An RSS feed of my Medium articles (https://tjgrapes.medium.com/)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^3.0.1
  google_fonts: ^4.0.3
  http: ^0.13.5 # https://pub.dev/packages/http
  webfeed: ^0.7.0 # https://pub.dev/packages/webfeed
  url_launcher: ^6.1.10 #https://pub.dev/packages/url_launcher
  just_audio: ^0.9.31
  flutter_share: ^2.0.0
  share: ^2.0.4
  font_awesome_flutter: ^10.4.0
  xml: ^5.0.2
  flutter_cache_manager: ^3.3.0
  firebase_core: ^2.9.0
  firebase_analytics: ^10.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/fonts/
  - assets/my_app_icon.png