// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUeGiEKFlE_wPwK6cxL7ShL2kLd5ewHNY',
    appId: '1:329807048327:web:fefefbf4616836f15e5222',
    messagingSenderId: '329807048327',
    projectId: 'radio20158-f636a',
    authDomain: 'radio20158-f636a.firebaseapp.com',
    storageBucket: 'radio20158-f636a.appspot.com',
    measurementId: 'G-SR4ZZLV0V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTXfGU5Y4MXDX28gWPLA8t5XhTZ5zw6AU',
    appId: '1:329807048327:android:fee2b53b7b0898fd5e5222',
    messagingSenderId: '329807048327',
    projectId: 'radio20158-f636a',
    storageBucket: 'radio20158-f636a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUO5gR81NxbPeO7a0gz-ElQlZn1SQs2OA',
    appId: '1:329807048327:ios:c4c92b00ed1d9e025e5222',
    messagingSenderId: '329807048327',
    projectId: 'radio20158-f636a',
    storageBucket: 'radio20158-f636a.appspot.com',
    iosClientId: '329807048327-jvmk548j618kjeajlof4oua42954ro5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.radio201582',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUO5gR81NxbPeO7a0gz-ElQlZn1SQs2OA',
    appId: '1:329807048327:ios:f7e70209fa3b3cb45e5222',
    messagingSenderId: '329807048327',
    projectId: 'radio20158-f636a',
    storageBucket: 'radio20158-f636a.appspot.com',
    iosClientId: '329807048327-4v6gvn8u1m3re5sljh9ec9l5i7c562f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.radio201582.RunnerTests',
  );
}
